name: I'm so lazy
description: Blogging about life habits and creating a better lifestyle 
meta_description: "I'm so lazy, a habits blog to help create a better lifestyle"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "https://imsolazy.com"
google_analytics: "UA-175858395-1"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
author: "Justin Bansal"

# Disqus config
disqus-shortname: "https-imsolazy-com"
url: "https://imsolazy.com"
