name: I'm so lazy
description: Blogging about bad habits 
meta_description: "I'm so lazy, blogging about bad habits"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "http://imsolazy.com"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Justin Bansal"

# Disqus config
disqus-shortname: ""
